import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f7f7f7',
    },
    inputWrap: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 0,
        minHeight: 40,
        position: 'relative',
    },
    clearIcon: {
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        height: '100%',
        zIndex: 10,
    },
    headerBtn: {
        marginHorizontal: 20,
    },
    headerBtnDisabled: {
        opacity: 0.5,
    },
    cancelText: {
        color: '#3d3d3dff',
        fontSize: 17,
        fontWeight: '500',
    },
    saveText: {
        color: '#267AFF',
        fontSize: 17,
        fontWeight: '500',
    },
    saveDisabled: {
        color: '#C7C7CC',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginTop: 8,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // backgroundColor: '#ddb7b7ff',
    },
    label: {
        fontSize: 16,
        color: '#222',
        fontWeight: '400',
    },
    input: {
        flex: 1,
        marginLeft: 16,
        fontSize: 16,
        color: '#222',
        borderBottomWidth: 0.5,
        borderBottomColor: '#e7e7e7ff',
        paddingVertical: 16,
    },
    sectionTitle: {
        fontSize: 13,
        color: '#363636ff',
        marginBottom: 5,
        marginLeft: 16,
    },
    typeListCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginHorizontal: 16,
        paddingVertical: 8,
        marginBottom: 16,
        paddingHorizontal: 0,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    typeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderColor: '#f2f2f2',
    },
    typeLabel: {
        fontSize: 16,
        color: '#222',
    },
    typeCheckWrap: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    typeCheck: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#2e7bff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    typeUncheck: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: '#d1d1d1',
        backgroundColor: '#fff',
    },
    addTypeBtn: {
        paddingHorizontal: 18,
        paddingVertical: 14,
    },
    addTypeText: {
        color: '#2e7bff',
        fontSize: 16,
        fontWeight: '500',
    },
});
