import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    experimental_backgroundImage: 'linear-gradient(165deg, #e8f0ffff 0%, #ffffffff 100%)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
    // backgroundColor: '#648797ff',
  },
  homeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    flex: 2,
    // backgroundColor: '#977f64ff',
  },
  homeIcon: {
    marginRight: 8,
  },
  homeName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
  },
  headerRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRightBtn: {
    // alignItems: 'center',
    marginLeft: 16,
    justifyContent: 'flex-end',
    // backgroundColor: '#7f9764ff',
  },
  section: {
    flex: 1,
    // backgroundColor: '#f7fafd',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  sectionContent: {
    paddingBottom: 32,
  },
  cardRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  card: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginRight: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    marginBottom: 0,
  },
  cardLast: {
    marginRight: 0,
  },
  weatherCard: {
    flex: 1,
    backgroundColor: '#e3f3ff',
    borderRadius: 16,
    padding: 18,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'flex-start',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
  },
  weatherTemp: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#2196f3',
    marginBottom: 4,
  },
  weatherDesc: {
    fontSize: 15,
    color: '#444',
    marginTop: 2,
    lineHeight: 20,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    marginBottom: 6,
  },
  cardValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2196f3',
  },
  cardSub: {
    fontSize: 14,
    color: '#888',
    marginTop: 2,
    marginBottom: 2,
  },
  addDataBtn: {
    marginTop: 10,
    backgroundColor: '#5ad6ff',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    alignSelf: 'flex-start',
  },
  addDataText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  bottomEditBtn: {
    marginTop: 24,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    width: '60%',
    alignSelf: 'center',
  },
  bottomEditText: {
    color: '#2196f3',
    fontWeight: 'bold',
    fontSize: 16,
  },
  emptyBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#888',
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 15,
    color: '#0000',
  },
  emptyBtn: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyImage:{
    width: 130,
    height: 130,
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  popupContainer: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    paddingTop: 18,
    // paddingBottom: 24,
    paddingHorizontal: 0,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 24,
    marginBottom: 10,
  },
  popupHomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  popupCheckIcon: {
    marginRight: 12,
  },
  popupCheckIconEmpty: {
    width: 22,
    height: 22,
    marginRight: 12,
  },
  popupHomeName: {
    fontSize: 17,
  },
  popupManageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderTopWidth: 0.5,
    borderTopColor: '#b4b4b4ff',
  },
  popupManageIcon: {
    marginRight: 12,
  },
  popupManageText: {
    fontSize: 17,
    fontWeight: '400',
  },

  // Lưới thiết bị
  deviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  deviceCard: {
    width: '47%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    position: 'relative',
  },
  deviceIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#f3f7fa',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    marginBottom: 2,
  },
  devicePowerBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    backgroundColor: '#e6f9f0',
    borderRadius: '50%',
    padding: 6,
  },

  menuPopup: {
        position: 'absolute',
        top: 55,
        right: 12,
        width: 200,
        backgroundColor: '#fff',
        borderRadius: 10,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        paddingVertical: 8,
        zIndex: 100,
    },
    arrowContainer: {
        position: 'absolute',
        top: -10,
        right: 15,
        width: 15,
        height: 10,
        overflow: 'hidden',
        zIndex: 200,
    },
    arrowShadow: {
        width: 11,
        height: 11,
        backgroundColor: '#fff',
        transform: [{ rotate: '45deg' }],
        position: 'absolute',
        top: 4,
        left: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 1,
        elevation: 4,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: 'transparent',
    },
    menuItemBorder: {
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    menuItemIcon: {
        marginRight: 14,
    },
    menuItemText: {
        fontSize: 16,
        color: '#222',
        fontWeight: '500',
    },
});

export default styles;
