import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F7F7FA',
        // backgroundColor: '#d7d7f5ff',
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 4,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 0,
        marginBottom: 14,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 20,
        paddingHorizontal: 16,
    },
    rowRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    label: {
        fontSize: 15,
        color: '#222',
        fontWeight: '500',
    },
    value: {
        fontSize: 14,
        color: '#888',
        fontWeight: '400',
    },
    subLabel: {
        fontSize: 12,
        color: '#888',
        marginTop: 2,
    },
    configBtn: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    deleteBtn: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginBottom: 32,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    deleteText: {
        color: '#D32F2F',
        fontSize: 16,
        fontWeight: '500',
    },
    configText: {
        color: '#1976d2',
        fontSize: 16,
        fontWeight: '500',
    },
    popupContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.18)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    popupBox: {
        backgroundColor: '#fff',
        borderRadius: 16,
        width: '85%',
        padding: 20,
    },
    espModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.35)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    espModalBox: {
        backgroundColor: '#fff',
        borderRadius: 20,
        width: '88%',
        paddingHorizontal: 28,
        paddingVertical: 16,
        shadowColor: '#1976d2',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 6,
    },
    espModalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1976d2',
        textAlign: 'center',
        marginBottom: 18,
    },
    espModalBtn: {
        backgroundColor: '#1976d2',
        borderRadius: 10,
        paddingVertical: 14,
        marginTop: 10,
        marginBottom: 4,
    },
    espModalBtnCancel: {
        backgroundColor: '#d8d8d8',
        borderRadius: 10,
        paddingVertical: 14,
        marginTop: 10,
        marginBottom: 4,
    },
    espModalBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        textAlign: 'center',
    },
    espModalBtnTextCancel: {
        color: '#222',
        fontSize: 16,
        fontWeight: '500',
        textAlign: 'center',
    },
    popupTitle: {
        fontSize: 18,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 18,
    },
    popupInput: {
        borderWidth: 1,
        borderColor: '#eee',
        borderRadius: 8,
        paddingHorizontal: 12,
        fontSize: 14,
        marginBottom: 24,
    },
    popupBtnRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    popupBtnCancel: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#f5f5f5',
        marginRight: 8,
    },
    popupBtnSave: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#fff',
    },
    popupBtnText: {
        textAlign: 'center',
        fontSize: 16,
    },
    espPopupBtnCancel: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#f5f5f5',
        marginRight: 8,
    },
    espPopupBtn: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#1976d2',
    },
});
