
import { StyleSheet, Platform } from 'react-native';


export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#b0b0e4ff',
  },
  backBtn: {
    padding: 8,
    borderRadius: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#222',
    textAlign: 'center',
    flex: 1,
  },
  confirmBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  confirmText: {
    color: '#267AFF',
    fontSize: 16,
    fontWeight: '500',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 22,
    marginHorizontal: 16,
    paddingHorizontal: 18,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    position: 'absolute',
    top: Platform.OS === 'ios' ? 70 : 60,
    left: 0,
    right: 0,
    zIndex: 3,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#222',
    backgroundColor: 'transparent',
    paddingVertical: 0,
    fontWeight: '500',
  },
  clearInputBtn: {
    marginLeft: 4,
    padding: 2,
    justifyContent: 'center',
    alignItems: 'center',
    height: 28,
    width: 28,
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  map: {
    flex: 1,
    borderRadius: 0,
    marginHorizontal: 0,
    marginBottom: 0,
    overflow: 'hidden',
  },
  centerPointerContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -16 }, { translateY: -16 }],
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: 32,
    height: 64,
    pointerEvents: 'none',
    backgroundColor: '#fff',
  },
  centerPointer: {
    width: 32,
    height: 32,
  },
  addressLabelOnMap: {
    position: 'absolute',
    top: -38,
    left: '50%',
    marginLeft: -60,
    minWidth: 80,
    maxWidth: 160,
    borderRadius: 14,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
    zIndex: 11,
  },
  addressLabelText: {
    fontSize: 15,
    color: '#222',
    fontWeight: '500',
    textAlign: 'center',
  },
});
